### ISSUE TITLE
issue during deployment to vercel

### ISSUE THREAD

**Issue by Mudl** [dword-design/nuxt-mail#72]
npm ERR! Could not install from "node_modules/@dword-design/functions/endent@github:dword-design/endent#fork" as it does not contain a package.json file.

not sure if related to this feature or not. but since dword-design is, I'm asking here if that is my fault or not. 
it works if I delete the package-lock.json form my branch. but not sure if that is supposed to be that way.

**Comment by dword-design** [comment]
@Mudl Weird. There were some problems with this fork recently, but I wasn't able to reproduce the issue yet. How come that a package-lock.json is on your branch? On mine there is only yarn.lock. Is it maybe related to that you try to use NPM instead of Yarn to install the packages? Best practice is to always use the package manager from the lock file in the repo.

**Comment by Mudl** [comment]
ok. works fine with yarn. thx.
